# Generated by Django 4.2 on 2023-06-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('idmovimiento', models.AutoField(db_column='idMovimiento', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('tipomovimiento', models.CharField(blank=True, db_column='tipoMovimiento', max_length=7, null=True)),
                ('montototal', models.DecimalField(blank=True, db_column='montoTotal', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'movimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimientodetalle',
            fields=[
                ('idmovimiento', models.IntegerField(db_column='idMovimiento', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('preciounitario', models.DecimalField(blank=True, db_column='precioUnitario', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'movimientodetalle',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Movimientos',
        ),
    ]
