# Generated by Django 4.2 on 2023-09-11 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_movimiento_movimientodetalle_delete_movimientos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('identrada', models.AutoField(db_column='idEntrada', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('montototal', models.DecimalField(blank=True, db_column='montoTotal', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'entrada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('idsalida', models.AutoField(db_column='idSalida', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('montototal', models.DecimalField(blank=True, db_column='montoTotal', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'salida',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Movimiento',
        ),
        migrations.DeleteModel(
            name='Movimientodetalle',
        ),
        migrations.CreateModel(
            name='Entradadetalle',
            fields=[
                ('identrada', models.OneToOneField(db_column='idEntrada', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='common.entrada')),
                ('cantidad', models.IntegerField()),
                ('preciounitario', models.DecimalField(blank=True, db_column='precioUnitario', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'entradadetalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salidadetalle',
            fields=[
                ('idsalida', models.OneToOneField(db_column='idSalida', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='common.salida')),
                ('cantidad', models.IntegerField()),
                ('preciounitario', models.DecimalField(blank=True, db_column='precioUnitario', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'salidadetalle',
                'managed': False,
            },
        ),
    ]
